name: Sync to Hugging Face Hub

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          if [ -z "$HF_TOKEN" ]; then
            echo "HF_TOKEN not found. Skipping Hugging Face Sync."
            exit 0
          fi
          git remote add space https://navari:$HF_TOKEN@huggingface.co/spaces/navari/age_gender_detection
          git push --force space main
